# Generated by Django 3.1.3 on 2021-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
