# Generated by Django 3.1.3 on 2021-03-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
